FROM continuumio/miniconda3:latest

RUN apt-get --allow-releaseinfo-change update
RUN apt-get -y install gcc

RUN conda config --add channels conda-forge
RUN conda config --set channel_priority strict

RUN conda install -n base conda-libmamba-solver
RUN conda config --set solver libmamba

ADD environment.yml /opt/spri_explore/environment.yml
RUN conda env create -f /opt/spri_explore/environment.yml -p /opt/conda/envs/film

COPY ./ /opt/spri_explore/
WORKDIR /opt/spri_explore

RUN echo "source activate film" > ~/.bashrc
ENV PATH=/opt/conda/envs/film/bin:$PATH
ENV CONDA_DEFAULT_ENV=film

CMD gunicorn --bind 0.0.0.0:$PORT --log-level=debug --preload wsgi:app