"""var types

Revision ID: 3f0b987d79ff
Revises: 8415ee5e38b2
Create Date: 2021-02-22 23:01:23.384196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f0b987d79ff'
down_revision = '8415ee5e38b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film_segment', 'dataset',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('film_segment', 'first_cbd',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('film_segment', 'first_frame',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('film_segment', 'flight',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('film_segment', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('film_segment_id_seq'::regclass)"))
    op.alter_column('film_segment', 'instrument_type',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('film_segment', 'last_cbd',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('film_segment', 'last_changed',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('film_segment', 'last_frame',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('film_segment', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('film_segment', 'path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('film_segment', 'reel',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('film_segment', 'scope_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('film_segment', 'updated_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('film_segment_version', 'first_cbd',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'first_frame',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'flight',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('film_segment_version', 'instrument_type',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'last_cbd',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'last_changed',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'last_frame',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'reel',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'scope_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'updated_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('flasklogin-users', 'created_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('flasklogin-users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('flasklogin-users', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('flasklogin-users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('flasklogin-users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('flasklogin-users', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('flasklogin-users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('transaction', 'issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('transaction', 'remote_addr',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'remote_addr',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transaction', 'issued_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('flasklogin-users', 'password',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('flasklogin-users', 'last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('flasklogin-users', 'last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('flasklogin-users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('flasklogin-users', 'first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('flasklogin-users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('flasklogin-users', 'created_on',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('film_segment_version', 'updated_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'scope_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'reel',
               existing_type=sa.String(length=100),
               type_=sa.BIGINT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'path',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'last_frame',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'last_changed',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'last_cbd',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'instrument_type',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=False)
    op.alter_column('film_segment_version', 'flight',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'first_frame',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment_version', 'first_cbd',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               autoincrement=False)
    op.alter_column('film_segment', 'updated_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'scope_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'reel',
               existing_type=sa.String(length=100),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'path',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'last_frame',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'last_changed',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('film_segment', 'last_cbd',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'instrument_type',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('film_segment_id_seq'::regclass)"))
    op.alter_column('film_segment', 'flight',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'first_frame',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'first_cbd',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('film_segment', 'dataset',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
