"""empty message

Revision ID: 7e8d2278b9d4
Revises: 9e057eef6196
Create Date: 2020-08-12 23:58:03.955050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e8d2278b9d4'
down_revision = '9e057eef6196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_16698_sqlite_autoindex_film_segment_1', table_name='film_segment')
    op.create_unique_constraint(None, 'film_segment', ['path'])
    op.alter_column('film_segment_version', 'operation_type',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.create_index(op.f('ix_film_segment_version_end_transaction_id'), 'film_segment_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_film_segment_version_operation_type'), 'film_segment_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_film_segment_version_transaction_id'), 'film_segment_version', ['transaction_id'], unique=False)
    op.drop_index('idx_16704_ix_film_segment_version_end_transaction_id', table_name='film_segment_version')
    op.drop_index('idx_16704_ix_film_segment_version_operation_type', table_name='film_segment_version')
    op.drop_index('idx_16704_ix_film_segment_version_transaction_id', table_name='film_segment_version')
    op.alter_column('flasklogin-users', 'created_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('flasklogin-users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('flasklogin-users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('flasklogin-users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('flasklogin-users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('flasklogin-users', 'write_permission',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('idx_16710_sqlite_autoindex_flasklogin-users_1', table_name='flasklogin-users')
    op.create_unique_constraint(None, 'flasklogin-users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flasklogin-users', type_='unique')
    op.create_index('idx_16710_sqlite_autoindex_flasklogin-users_1', 'flasklogin-users', ['email'], unique=True)
    op.alter_column('flasklogin-users', 'write_permission',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('flasklogin-users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('flasklogin-users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('flasklogin-users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('flasklogin-users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('flasklogin-users', 'created_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index('idx_16704_ix_film_segment_version_transaction_id', 'film_segment_version', ['transaction_id'], unique=False)
    op.create_index('idx_16704_ix_film_segment_version_operation_type', 'film_segment_version', ['operation_type'], unique=False)
    op.create_index('idx_16704_ix_film_segment_version_end_transaction_id', 'film_segment_version', ['end_transaction_id'], unique=False)
    op.drop_index(op.f('ix_film_segment_version_transaction_id'), table_name='film_segment_version')
    op.drop_index(op.f('ix_film_segment_version_operation_type'), table_name='film_segment_version')
    op.drop_index(op.f('ix_film_segment_version_end_transaction_id'), table_name='film_segment_version')
    op.alter_column('film_segment_version', 'operation_type',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_constraint(None, 'film_segment', type_='unique')
    op.create_index('idx_16698_sqlite_autoindex_film_segment_1', 'film_segment', ['path'], unique=True)
    # ### end Alembic commands ###
