"""Greenland permissions

Revision ID: 8415ee5e38b2
Revises: 7e8d2278b9d4
Create Date: 2021-02-22 22:00:17.976698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8415ee5e38b2'
down_revision = '7e8d2278b9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Note: This is slightly customized to set default values for the new dataset and view_greenland columns

    op.add_column('film_segment', sa.Column('dataset', sa.String(length=100), nullable=True))
    op.add_column('film_segment_version', sa.Column('dataset', sa.String(length=100), autoincrement=False, nullable=True))
    op.add_column('flasklogin-users', sa.Column('view_greenland', sa.Boolean(), nullable=True))

    op.execute("""UPDATE "film_segment" SET dataset='antarctica'""")
    op.alter_column('film_segment', 'dataset', nullable=False)
    op.execute('UPDATE "flasklogin-users" SET view_greenland=false')
    op.alter_column('flasklogin-users', 'view_greenland', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flasklogin-users', 'view_greenland')
    op.drop_column('film_segment_version', 'dataset')
    op.drop_column('film_segment', 'dataset')
    # ### end Alembic commands ###
