"""empty message

Revision ID: 9e057eef6196
Revises: 
Create Date: 2020-04-23 00:57:39.810904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e057eef6196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('reel', sa.Integer(), nullable=True),
    sa.Column('first_frame', sa.Integer(), nullable=True),
    sa.Column('last_frame', sa.Integer(), nullable=True),
    sa.Column('first_cbd', sa.Integer(), nullable=True),
    sa.Column('last_cbd', sa.Integer(), nullable=True),
    sa.Column('flight', sa.Integer(), nullable=True),
    sa.Column('is_junk', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('scope_type', sa.CHAR(), nullable=True),
    sa.Column('instrument_type', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('film_segment_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('path', sa.String(length=300), autoincrement=False, nullable=True),
    sa.Column('reel', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('first_frame', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_frame', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('first_cbd', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('last_cbd', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('flight', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('is_junk', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('needs_review', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('scope_type', sa.CHAR(), autoincrement=False, nullable=True),
    sa.Column('instrument_type', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.String(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('last_changed', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_film_segment_version_end_transaction_id'), 'film_segment_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_film_segment_version_operation_type'), 'film_segment_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_film_segment_version_transaction_id'), 'film_segment_version', ['transaction_id'], unique=False)
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('write_permission', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('flasklogin-users')
    op.drop_index(op.f('ix_film_segment_version_transaction_id'), table_name='film_segment_version')
    op.drop_index(op.f('ix_film_segment_version_operation_type'), table_name='film_segment_version')
    op.drop_index(op.f('ix_film_segment_version_end_transaction_id'), table_name='film_segment_version')
    op.drop_table('film_segment_version')
    op.drop_table('film_segment')
    # ### end Alembic commands ###
