"""add date

Revision ID: b843fc84bb11
Revises: 3f0b987d79ff
Create Date: 2021-02-23 21:10:30.170756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b843fc84bb11'
down_revision = '3f0b987d79ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film_segment', sa.Column('raw_date', sa.Integer(), nullable=True))
    op.add_column('film_segment', sa.Column('raw_mode', sa.Integer(), nullable=True))
    op.add_column('film_segment', sa.Column('raw_time', sa.Integer(), nullable=True))
    op.add_column('film_segment_version', sa.Column('raw_date', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('film_segment_version', sa.Column('raw_mode', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('film_segment_version', sa.Column('raw_time', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film_segment_version', 'raw_time')
    op.drop_column('film_segment_version', 'raw_mode')
    op.drop_column('film_segment_version', 'raw_date')
    op.drop_column('film_segment', 'raw_time')
    op.drop_column('film_segment', 'raw_mode')
    op.drop_column('film_segment', 'raw_date')
    # ### end Alembic commands ###
